/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Heroes;
import Modelo.Super_X;
import Modelo.Villanos;
import Vista.Pantalla;


/**
 *
 * @author Jessie
 */
public class Pantalla extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuestroPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_resultado = new javax.swing.JTextArea();
        panelVillano = new javax.swing.JLabel();
        panelHeroe = new javax.swing.JLabel();
        boton = new javax.swing.JButton();

        nuestroPanel.setBackground(new java.awt.Color(192, 36, 37));
        nuestroPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nuestroPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuestroPanel.setFocusCycleRoot(true);
        nuestroPanel.setPreferredSize(new java.awt.Dimension(700, 542));

        titulo.setBackground(new java.awt.Color(192, 36, 37));
        titulo.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titulo.setText("LET THE GAME BEGIN");
        titulo.setBorder(null);
        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });

        texto_resultado.setBackground(new java.awt.Color(153, 0, 0));
        texto_resultado.setColumns(20);
        texto_resultado.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        texto_resultado.setLineWrap(true);
        texto_resultado.setRows(5);
        texto_resultado.setBorder(null);
        jScrollPane1.setViewportView(texto_resultado);

        panelVillano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cruela.png"))); // NOI18N

        panelHeroe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHeroe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rober.png"))); // NOI18N

        boton.setBackground(new java.awt.Color(0, 0, 0));
        boton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/click1.png"))); // NOI18N
        boton.setText("Fight!");
        boton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton.setContentAreaFilled(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        boton.setIconTextGap(6);
        boton.setOpaque(true);
        boton.setPreferredSize(new java.awt.Dimension(62, 29));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuestroPanelLayout = new javax.swing.GroupLayout(nuestroPanel);
        nuestroPanel.setLayout(nuestroPanelLayout);
        nuestroPanelLayout.setHorizontalGroup(
            nuestroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuestroPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuestroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nuestroPanelLayout.createSequentialGroup()
                        .addComponent(panelVillano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nuestroPanelLayout.setVerticalGroup(
            nuestroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuestroPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuestroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelVillano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHeroe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuestroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuestroPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        //Esto lo deje acá porque es lo que después quiero que veamos como hacer que se vea siempre
        texto_resultado.setText("Mortal Kombat 2.0");        
        texto_resultado.append("\nBy Camm & Marto");
                
        
        //Creación de Heroes
        Heroes h1=new Heroes();
        h1.setEnergia(100);
        h1.setPais_origen("Inglaterra");
        h1.setNombre("Rober-Tone");
        h1.setHabilidad_ppal("Decibeles Mortales");
        h1.setIndice_bondad(9);
        
        Heroes h2=new Heroes("Halcón del desierto","Nueva Zelanda", "Ojos láser", 100, 8);        
        
        //Creación de Villanos
        Villanos v1=new Villanos();
        v1.setEnergia(100);
        v1.setNombre("Cruela");
        v1.setPais_origen("Italia");
        v1.setHabilidad_ppal("Vuela muy alto");
        v1.setIndice_maldad(10);
        
        Villanos v2=new Villanos("Destructor", "Nueva York", "Fuerza extrema",100, 9);        
        
        texto_resultado.append("\n\nPRESENTACIÓN DE PERSONAJES:"); 
        
        
        //Lista de luchadores
        String [] lista = new String [4];
        
        lista[0]= "HEROES: \n"+h1.toString() + " Indice de Bondad: "+h1.getIndice_bondad();
        lista[1]= h2.toString() + " Indice de Bondad: "+h2.getIndice_bondad()+"\n";        
        lista[2]= "VILLANOS: \n"+v1.toString() + " Indice de Maldad: "+v1.getIndice_maldad();
        lista[3]= v2.toString() + " Indice de Maldad: "+v2.getIndice_maldad();
        
        //Recorro la lista
        for (int i=0; i<4; i++) {                                      
            texto_resultado.append("\n\n"+lista[i]);                 
        }                        
                
        //Elección al azar de los luchadores
        int numMin = 1;     //el indice minimo de la lista
        int numMax = 4;    //el indice maximo de la lista        
        int luch1 = (int)Math.floor(Math.random()*(numMax - numMin +1)+(numMin));            
        int luch2 = (int)Math.floor(Math.random()*(numMax - numMin +1)+(numMin));
        
        //Validar para no repetir personajes
        if (luch2 == luch1) {
            luch2 = (int)Math.floor(Math.random()*(numMax - numMin +1)+(numMin));                
        }
        
        texto_resultado.append("\n\nQUE COMIENCE EL JUEGO!");     
        texto_resultado.append("\nHoy se enfrentan..."); 
        
        int luchUnoEnergia = 0;
        int luchDosEnergia = 0;
        
        switch(luch1) {
            case 1:                
                texto_resultado.append(h1.getNombre());                
                luchUnoEnergia = h1.getEnergia();
                break;
            case 2:                
                texto_resultado.append(h2.getNombre());
                luchUnoEnergia = h2.getEnergia();
                break;                
            case 3:                
                texto_resultado.append(v1.getNombre());
                luchUnoEnergia = v1.getEnergia();
                break;
            case 4:                
                texto_resultado.append(v2.getNombre());
                luchUnoEnergia = v2.getEnergia();
                break;
            default:
                texto_resultado.append("¡Error!");
                break;                
        }       
        
        switch(luch2) {
            case 1:                
                texto_resultado.append(" vs. "+h1.getNombre());
                luchDosEnergia = h1.getEnergia();
                break;

            case 2:                
                texto_resultado.append(" vs. "+h2.getNombre());
                luchDosEnergia = h2.getEnergia();
                break;                
            case 3:                
                texto_resultado.append(" vs. "+v1.getNombre());
                luchDosEnergia = v1.getEnergia();
                break;
            case 4:                
                texto_resultado.append(" vs. "+v2.getNombre());
                luchDosEnergia = v2.getEnergia();
                break;
            default:
                texto_resultado.append("¡Error!");
                break;                
        }                
        
        texto_resultado.append("Luch1: "+luch1+" vs. "+"Luch2: "+luch2);
        System.out.println();
        texto_resultado.append("\n\nAmbos luchadores comienzan el encuentro con una energía del 100%");
        texto_resultado.append("LET'S FIGHT!");                               
        
        
        
        //while ((h1.getEnergia() > 0) || (v1.getEnergia() > 0) || (h2.getEnergia() > 0) || (v2.getEnergia() > 0)) {
        while ((luchUnoEnergia > 0) && (luchDosEnergia > 0)) {
            int minimo = 1;
            int maximo = 4;
            int golpeHeroes = Super_X.generarNumeroAleatorio(minimo, maximo);
            int golpeVillanos = Super_X.generarNumeroAleatorio(minimo, maximo);
            int golpe;
            
            switch(golpeHeroes) {
                case 1:
                    golpe = h1.debilitar(v1.atacarVillano_1());
                    texto_resultado.append("----- A " + h1.getNombre() + " le queda " +golpe +  "% de energía.");
                    break;
                case 2:
                    golpe = h1.debilitar(v1.atacarVillano_2());
                    texto_resultado.append("----- A " + h1.getNombre() + " le queda " +golpe +  "% de energía.");
                    break;
                case 3:
                    golpe = h1.debilitar(v1.atacarVillano_3());
                    texto_resultado.append("----- A " + h1.getNombre() + " le queda " +golpe +  "% de energía.");
                    break;
                case 4:
                    golpe = h1.debilitar(v1.atacarVillano_4());
                    texto_resultado.append("----- A " + h1.getNombre() + " le queda " +golpe +  "% de energía.");
                    break;
                default:
                    break;
            }
            switch(golpeVillanos) {
                case 1:
                    golpe = v1.debilitar(h1.atacarHeroe_1());
                    texto_resultado.append("----- A " + v1.getNombre() + " le queda " +golpe +  "% de energía.");
                    texto_resultado.append("***************************************************************************");
                    break;
                case 2:
                    golpe = v1.debilitar(h1.atacarHeroe_2());
                    texto_resultado.append("----- A " + v1.getNombre() + " le queda " +golpe +  "% de energía.");
                    texto_resultado.append("***************************************************************************");
                    break;
                case 3:
                    golpe = v1.debilitar(h1.atacarHeroe_3());
                    texto_resultado.append("----- A " + v1.getNombre() + " le queda " +golpe +  "% de energía.");
                    texto_resultado.append("***************************************************************************");
                    break;
                case 4:
                    golpe = v1.debilitar(h1.atacarHeroe_4());
                    texto_resultado.append("----- A " + v1.getNombre() + " le queda " +golpe +  "% de energía.");
                    texto_resultado.append("***************************************************************************");
                    break;
                default:
                    break;
            }
            
            int energia_actual_Villanos=v1.getEnergia();
            int energia_actual_Heroes=h1.getEnergia();
            if ((energia_actual_Villanos <= 0) && (energia_actual_Heroes > 0)) {
                texto_resultado.append(h1.getNombre()+ " ha vencido a " + v1.getNombre() + "!! "
                + v1.getNombre() + " ha muerto." + " May the forth be with her.");
            }
            else if ((energia_actual_Heroes <= 0) && (energia_actual_Villanos > 0)) {
                texto_resultado.append(v1.getNombre()+ " ha vencido a " + h1.getNombre() + "!! "
                + h1.getNombre() + " ha muerto." + " May the forth be with him.");
            }
            else if((energia_actual_Villanos <=0) && (energia_actual_Heroes <=0)) {
                texto_resultado.append("Ambos son PERDEDORES, han muerto!!!!"
                + " Ahora pelean para el más allá. Bienvenidos al mundo ZOMBIE.");
            }
        }
    
    }//GEN-LAST:event_botonActionPerformed

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nuestroPanel;
    private javax.swing.JLabel panelHeroe;
    private javax.swing.JLabel panelVillano;
    private javax.swing.JTextArea texto_resultado;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}


